/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.giaodien_maven;

/**
 *
 * @author Admin
 */
public class QLGD extends javax.swing.JFrame {

    /** Creates new form QLGD2 */
    public QLGD() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbUserName = new javax.swing.JLabel();
        lbQuanLyGiaoDich = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbChonChuDeTimKiem = new javax.swing.JLabel();
        cbChonChuDeTimKiem = new javax.swing.JComboBox<>();
        txtNhapThongTinTimKiem = new javax.swing.JTextField();
        lbNhapThongTinTimKiem = new javax.swing.JLabel();
        lbTuNgay = new javax.swing.JLabel();
        txtNhapNgayBD = new javax.swing.JTextField();
        lbDenNgay = new javax.swing.JLabel();
        txtNhapNgayKT = new javax.swing.JTextField();
        lbKhongTimThay = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbThemLoaiGiaoDich = new javax.swing.JLabel();
        lbThemNguonTien = new javax.swing.JLabel();
        lbThemSoTien = new javax.swing.JLabel();
        lbThemNgayGiaoDich = new javax.swing.JLabel();
        txtThemNgayGiaoDich = new javax.swing.JTextField();
        btnThemGiaoDich = new javax.swing.JButton();
        txtThemSoTien = new javax.swing.JTextField();
        cbChonLoaiGiaoDich = new javax.swing.JComboBox<>();
        txtThemNguonTien = new javax.swing.JTextField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lbThemThongTinNguonTien = new javax.swing.JLabel();
        lbMaNguonTien = new javax.swing.JLabel();
        lbThemNguonTien2 = new javax.swing.JLabel();
        txtNhapMaNguonTien = new javax.swing.JTextField();
        txtNhapNguonTien2 = new javax.swing.JTextField();
        btnHoanTat = new javax.swing.JButton();
        lbThemGiaoDichThanhCong = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbThemMaLoai = new javax.swing.JLabel();
        lbThemSoTienMuonChi = new javax.swing.JLabel();
        txtThemMaLoai = new javax.swing.JTextField();
        txtThemSoTienMuonChi = new javax.swing.JTextField();
        btnThemLoaiGiaoDich = new javax.swing.JButton();
        lbThemLoaiGiaoDichThanhCong = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTrangChu = new javax.swing.JMenu();
        menuQuanLyTraCuu = new javax.swing.JMenu();
        menuXemTrangThaiTaiChinh = new javax.swing.JMenu();
        menuBaoCaoTaiChinh = new javax.swing.JMenu();
        menuThongKe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        lbUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-32.png"))); // NOI18N
        lbUserName.setText("User_name");

        lbQuanLyGiaoDich.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbQuanLyGiaoDich.setForeground(new java.awt.Color(255, 255, 255));
        lbQuanLyGiaoDich.setText("Quản lý giao dịch");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lbQuanLyGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuanLyGiaoDich)
                    .addComponent(lbUserName))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Loại giao dịch", "Nguồn tiền", "Số tiền giao dịch", "Ngày giao dịch"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lbChonChuDeTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kính lúp.png"))); // NOI18N
        lbChonChuDeTimKiem.setText("Chọn chủ đề tìm kiếm");

        cbChonChuDeTimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại giao dịch", "Nguồn tiền", "Số tiền" }));

        txtNhapThongTinTimKiem.setToolTipText("Nhập thông tin tìm kiếm");

        lbNhapThongTinTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kính lúp.png"))); // NOI18N
        lbNhapThongTinTimKiem.setText("Nhập thông tin tìm kiếm");

        lbTuNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kính lúp.png"))); // NOI18N
        lbTuNgay.setText("Từ ngày");

        txtNhapNgayBD.setToolTipText("Nhập ngày bắt đầu");

        lbDenNgay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kính lúp.png"))); // NOI18N
        lbDenNgay.setText("Đến ngày");
        lbDenNgay.setToolTipText("");

        txtNhapNgayKT.setToolTipText("Nhập ngày kết thúc");

        lbKhongTimThay.setForeground(new java.awt.Color(255, 0, 0));
        lbKhongTimThay.setText("Không tìm thấy.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbChonChuDeTimKiem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbChonChuDeTimKiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNhapThongTinTimKiem)
                                .addComponent(lbNhapThongTinTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                            .addGap(84, 84, 84)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNhapNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lbDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16))
                                .addComponent(txtNhapNgayKT))))
                    .addComponent(lbKhongTimThay, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbChonChuDeTimKiem)
                    .addComponent(lbNhapThongTinTimKiem)
                    .addComponent(lbTuNgay)
                    .addComponent(lbDenNgay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChonChuDeTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhapThongTinTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhapNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNhapNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lbKhongTimThay)
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Tra cứu giao dịch", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbThemLoaiGiaoDich.setText("Chọn loại giao dịch");

        lbThemNguonTien.setText("Nguồn tiền");

        lbThemSoTien.setText("Số tiền");

        lbThemNgayGiaoDich.setText("Ngày giao dịch");

        txtThemNgayGiaoDich.setToolTipText("Nhập ngày giao dịch");

        btnThemGiaoDich.setBackground(new java.awt.Color(0, 102, 51));
        btnThemGiaoDich.setForeground(new java.awt.Color(255, 255, 255));
        btnThemGiaoDich.setText("Thêm");

        txtThemSoTien.setToolTipText("Nhập số tiền giao dịch");

        cbChonLoaiGiaoDich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP_Food", "SP_Study", "SP_Shopee", "InSt_Sell", "InSt_Buy", "Loan_pay", "Loan_fee_pay" }));

        txtThemNguonTien.setToolTipText("Nhập nguồn tiền");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbThemThongTinNguonTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbThemThongTinNguonTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbThemThongTinNguonTien.setText("Thêm thông tin nguồn tiền");

        lbMaNguonTien.setText("Mã");

        lbThemNguonTien2.setText("Nguồn tiền");

        txtNhapMaNguonTien.setToolTipText("Nhập mã");

        txtNhapNguonTien2.setToolTipText("nhập nguồn tiền");

        btnHoanTat.setBackground(new java.awt.Color(0, 102, 51));
        btnHoanTat.setForeground(new java.awt.Color(255, 255, 255));
        btnHoanTat.setText("Hoàn tất");

        jLayeredPane1.setLayer(lbThemThongTinNguonTien, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbMaNguonTien, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lbThemNguonTien2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNhapMaNguonTien, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtNhapNguonTien2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnHoanTat, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbThemThongTinNguonTien, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lbMaNguonTien, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(txtNhapMaNguonTien))
                            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                                .addComponent(lbThemNguonTien2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNhapNguonTien2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHoanTat)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(lbThemThongTinNguonTien, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaNguonTien)
                    .addComponent(txtNhapMaNguonTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThemNguonTien2)
                    .addComponent(txtNhapNguonTien2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHoanTat)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        lbThemGiaoDichThanhCong.setForeground(new java.awt.Color(0, 102, 51));
        lbThemGiaoDichThanhCong.setText("Thêm giao dịch thành công.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbThemGiaoDichThanhCong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemGiaoDich))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbThemLoaiGiaoDich, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addComponent(lbThemSoTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbThemNgayGiaoDich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbThemNguonTien, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbChonLoaiGiaoDich, 0, 259, Short.MAX_VALUE)
                            .addComponent(txtThemNgayGiaoDich)
                            .addComponent(txtThemSoTien)
                            .addComponent(txtThemNguonTien))))
                .addGap(50, 50, 50)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbChonLoaiGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThemLoaiGiaoDich))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbThemNguonTien)
                            .addComponent(txtThemNguonTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbThemSoTien)
                            .addComponent(txtThemSoTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThemNgayGiaoDich)
                    .addComponent(txtThemNgayGiaoDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThemGiaoDich)
                    .addComponent(lbThemGiaoDichThanhCong))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm giao dịch", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbThemMaLoai.setText("Mã loại");

        lbThemSoTienMuonChi.setText("Số tiền muốn chi");

        txtThemMaLoai.setToolTipText("Nhập mã loại");

        txtThemSoTienMuonChi.setToolTipText("Nhập số tiền");

        btnThemLoaiGiaoDich.setBackground(new java.awt.Color(0, 102, 51));
        btnThemLoaiGiaoDich.setForeground(new java.awt.Color(255, 255, 255));
        btnThemLoaiGiaoDich.setText("Thêm");

        lbThemLoaiGiaoDichThanhCong.setForeground(new java.awt.Color(0, 102, 51));
        lbThemLoaiGiaoDichThanhCong.setText("Thêm loại giao dịch thành công.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lbThemLoaiGiaoDichThanhCong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(btnThemLoaiGiaoDich))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbThemSoTienMuonChi, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(lbThemMaLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtThemMaLoai)
                            .addComponent(txtThemSoTienMuonChi, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThemMaLoai)
                    .addComponent(txtThemMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThemSoTienMuonChi)
                    .addComponent(txtThemSoTienMuonChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThemLoaiGiaoDich)
                    .addComponent(lbThemLoaiGiaoDichThanhCong))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm loại giao dịch", jPanel4);

        menuTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/black_home32.png"))); // NOI18N
        menuTrangChu.setText("Trang chủ");
        jMenuBar1.add(menuTrangChu);

        menuQuanLyTraCuu.setText("Quản lý & Tra cứu");
        jMenuBar1.add(menuQuanLyTraCuu);

        menuXemTrangThaiTaiChinh.setText("Xem trạng thái tài chính");
        jMenuBar1.add(menuXemTrangThaiTaiChinh);

        menuBaoCaoTaiChinh.setText("Báo cáo tài chính");
        jMenuBar1.add(menuBaoCaoTaiChinh);

        menuThongKe.setText("Thống kê");
        jMenuBar1.add(menuThongKe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLGD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLGD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHoanTat;
    private javax.swing.JButton btnThemGiaoDich;
    private javax.swing.JButton btnThemLoaiGiaoDich;
    private javax.swing.JComboBox<String> cbChonChuDeTimKiem;
    private javax.swing.JComboBox<String> cbChonLoaiGiaoDich;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbChonChuDeTimKiem;
    private javax.swing.JLabel lbDenNgay;
    private javax.swing.JLabel lbKhongTimThay;
    private javax.swing.JLabel lbMaNguonTien;
    private javax.swing.JLabel lbNhapThongTinTimKiem;
    private javax.swing.JLabel lbQuanLyGiaoDich;
    private javax.swing.JLabel lbThemGiaoDichThanhCong;
    private javax.swing.JLabel lbThemLoaiGiaoDich;
    private javax.swing.JLabel lbThemLoaiGiaoDichThanhCong;
    private javax.swing.JLabel lbThemMaLoai;
    private javax.swing.JLabel lbThemNgayGiaoDich;
    private javax.swing.JLabel lbThemNguonTien;
    private javax.swing.JLabel lbThemNguonTien2;
    private javax.swing.JLabel lbThemSoTien;
    private javax.swing.JLabel lbThemSoTienMuonChi;
    private javax.swing.JLabel lbThemThongTinNguonTien;
    private javax.swing.JLabel lbTuNgay;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JMenu menuBaoCaoTaiChinh;
    private javax.swing.JMenu menuQuanLyTraCuu;
    private javax.swing.JMenu menuThongKe;
    private javax.swing.JMenu menuTrangChu;
    private javax.swing.JMenu menuXemTrangThaiTaiChinh;
    private javax.swing.JTextField txtNhapMaNguonTien;
    private javax.swing.JTextField txtNhapNgayBD;
    private javax.swing.JTextField txtNhapNgayKT;
    private javax.swing.JTextField txtNhapNguonTien2;
    private javax.swing.JTextField txtNhapThongTinTimKiem;
    private javax.swing.JTextField txtThemMaLoai;
    private javax.swing.JTextField txtThemNgayGiaoDich;
    private javax.swing.JTextField txtThemNguonTien;
    private javax.swing.JTextField txtThemSoTien;
    private javax.swing.JTextField txtThemSoTienMuonChi;
    // End of variables declaration//GEN-END:variables

}
