/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.giaodien_maven;

/**
 *
 * @author Admin
 */
public class QLDTTT2 extends javax.swing.JFrame {

    /**
     * Creates new form QLDTTT2
     */
    public QLDTTT2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbUserName = new javax.swing.JLabel();
        lbQuanLyDauTuTichTru = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        lbChonLoaiDauTuTichTru = new javax.swing.JLabel();
        cbChonLoaiDauTuTichTru = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbThemLoai = new javax.swing.JLabel();
        lbThemGiaMuaVao = new javax.swing.JLabel();
        lbThemTongSoLuong = new javax.swing.JLabel();
        lbThemDonVi = new javax.swing.JLabel();
        cbThemLoai = new javax.swing.JComboBox<>();
        txtThemGiaMuaVao = new javax.swing.JTextField();
        txtThemTongSoLuong = new javax.swing.JTextField();
        txtThemDonVi = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        lbThemThanhCong = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuTrangChu = new javax.swing.JMenu();
        menuQuanLyTraCuu = new javax.swing.JMenu();
        menuXemTrangThaiTaiChinh = new javax.swing.JMenu();
        menuBaoCaoTaiChinh = new javax.swing.JMenu();
        menuThongKe = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        lbUserName.setForeground(new java.awt.Color(255, 255, 255));
        lbUserName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-user-32.png"))); // NOI18N
        lbUserName.setText("User_name");

        lbQuanLyDauTuTichTru.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbQuanLyDauTuTichTru.setForeground(new java.awt.Color(255, 255, 255));
        lbQuanLyDauTuTichTru.setText("Quản lý đầu tư & tích trữ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(lbQuanLyDauTuTichTru, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbUserName)
                    .addComponent(lbQuanLyDauTuTichTru))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbChonLoaiDauTuTichTru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kính lúp.png"))); // NOI18N
        lbChonLoaiDauTuTichTru.setText("Chọn loại đầu tư & tích trữ");

        cbChonLoaiDauTuTichTru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "ST_VCBF-FIF", "ST_GOLD", "ST_USD", "IN_BID", "IN_FPT", "IN_HVN", "IN_SSI-SCA", "IN_BTC", "IN_ETH", "IN_BUSINESS", "Short_BTC", "Short_Gold", "Short_ETH", "Short_BID", "Short_FPT" }));
        cbChonLoaiDauTuTichTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChonLoaiDauTuTichTruActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Loại", "Giá mua vào", "Tổng số lượng", "Đơn vị"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbChonLoaiDauTuTichTru, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addComponent(cbChonLoaiDauTuTichTru, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbChonLoaiDauTuTichTru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbChonLoaiDauTuTichTru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Danh sách đầu tư & tích trữ", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbThemLoai.setText("Loại");

        lbThemGiaMuaVao.setText("Giá mua vào");

        lbThemTongSoLuong.setText("Tổng số lượng");

        lbThemDonVi.setText("Đơn vị");

        cbThemLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ST_VCBF-FIF", "ST_GOLD", "ST_USD", "IN_BID", "IN_FPT", "IN_HVN", "IN_SSI-SCA", "IN_BTC", "IN_ETH", "IN_BUSINESS", "Short_BTC", "Short_Gold", "Short_ETH", "Short_BID", "Short_FPT" }));
        cbThemLoai.setToolTipText("Chọn loại");

        txtThemGiaMuaVao.setToolTipText("Nhập giá mua vào");

        txtThemTongSoLuong.setToolTipText("Nhập tổng số lượng");

        txtThemDonVi.setToolTipText("Nhập đơn vị");

        btnThem.setBackground(new java.awt.Color(0, 102, 51));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");

        lbThemThanhCong.setForeground(new java.awt.Color(0, 102, 51));
        lbThemThanhCong.setText("Thêm thành công.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbThemThanhCong, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                        .addComponent(btnThem))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbThemGiaMuaVao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbThemLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbThemTongSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(lbThemDonVi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbThemLoai, 0, 300, Short.MAX_VALUE)
                            .addComponent(txtThemGiaMuaVao)
                            .addComponent(txtThemTongSoLuong)
                            .addComponent(txtThemDonVi))))
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThemLoai)
                    .addComponent(cbThemLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThemGiaMuaVao)
                    .addComponent(txtThemGiaMuaVao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThemTongSoLuong)
                    .addComponent(txtThemTongSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbThemDonVi)
                    .addComponent(txtThemDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(lbThemThanhCong))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sửa", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Xóa", jPanel5);

        menuTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/black_home32.png"))); // NOI18N
        menuTrangChu.setText("Trang chủ");
        jMenuBar1.add(menuTrangChu);

        menuQuanLyTraCuu.setText("Quản lý & Tra cứu");
        jMenuBar1.add(menuQuanLyTraCuu);

        menuXemTrangThaiTaiChinh.setText("Xem trạng thái tài chính");
        jMenuBar1.add(menuXemTrangThaiTaiChinh);

        menuBaoCaoTaiChinh.setText("Báo cáo tài chính");
        jMenuBar1.add(menuBaoCaoTaiChinh);

        menuThongKe.setText("Thống kê");
        jMenuBar1.add(menuThongKe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbChonLoaiDauTuTichTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChonLoaiDauTuTichTruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChonLoaiDauTuTichTruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDTTT2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDTTT2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDTTT2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDTTT2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDTTT2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbChonLoaiDauTuTichTru;
    private javax.swing.JComboBox<String> cbThemLoai;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbChonLoaiDauTuTichTru;
    private javax.swing.JLabel lbQuanLyDauTuTichTru;
    private javax.swing.JLabel lbThemDonVi;
    private javax.swing.JLabel lbThemGiaMuaVao;
    private javax.swing.JLabel lbThemLoai;
    private javax.swing.JLabel lbThemThanhCong;
    private javax.swing.JLabel lbThemTongSoLuong;
    private javax.swing.JLabel lbUserName;
    private javax.swing.JMenu menuBaoCaoTaiChinh;
    private javax.swing.JMenu menuQuanLyTraCuu;
    private javax.swing.JMenu menuThongKe;
    private javax.swing.JMenu menuTrangChu;
    private javax.swing.JMenu menuXemTrangThaiTaiChinh;
    private javax.swing.JTextField txtThemDonVi;
    private javax.swing.JTextField txtThemGiaMuaVao;
    private javax.swing.JTextField txtThemTongSoLuong;
    // End of variables declaration//GEN-END:variables
}
